### ISSUE TITLE
Pie-chart not visible if in <span>

### ISSUE THREAD

**Issue by ozzi-** [n3-charts/pie-chart#22]
If i use something like the following

```
<span ng-show="initiative.already_voted">
    <pie-chart data="piedata" options="pieoptions"></pie-chart>
</span>
```

the pie isn't rendered.
However a div works perfectly fine. It isn't a CSS issue.

```
<div ng-show="initiative.already_voted">
    <pie-chart data="piedata" options="pieoptions"></pie-chart>
</div>
```

**Comment by lorem--ipsum** [comment]
`div`s and `span`s have a different default `display` attribute. Have you tried to fiddle with that ?

**Comment by ozzi-** [comment]
display:  

> block          - works
> inline-block - works
> inline           - does not work

However imho it shouldn't matter.
Anyways, great work :+1:
