### ISSUE TITLE
Set height of svg

### ISSUE THREAD

**Issue by dasaanudeep** [n3-charts/pie-chart#5]
How to  set the height of svg, when we add this
`<pie-chart data="data" options="options" >`
default height is considered, Is it possible to change the height

**Comment by dkushner** [comment]
@dasaanudeep, care to share with the rest of the community exactly how you solved it? That is, after all, the point of GitHub Issues.

**Comment by cubotar** [comment]
The pie-chart will inherit css from parent 
doing this :
<div style="width:150px;height:150px">
 <pie-chart data="data" options="options"></pie-chart>
</div>
will give the svg 150px as width and 150px as height
And yeah thanks @dasaanudeep for sharing :p

**Comment by sdhintGIT** [comment]
argh after a very frustrating hour and a half of my life, i have discovered an issue with the chart height being within a div that contains an ng-show with variable value attribute. it completely ignores the height set, removing ng-show and the chart is the value i set.

changed implementation to jquery .show and .hide on a new class and that workaround was sufficient.

**Comment by cubotar** [comment]
try an ng-if instead of ng-show
